# Generated by Django 4.2.5 on 2023-10-19 13:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0002_genre_publishinghouse_serie_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('cover', models.ImageField(upload_to='book_images/%Y/%m/%d', verbose_name='Cover')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('year_of_publishing', models.IntegerField(verbose_name='Year of publishing')),
                ('page', models.IntegerField(verbose_name='Pages')),
                ('format', models.CharField(max_length=50, verbose_name='Format')),
                ('isbn', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ISBN')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('age', models.IntegerField(verbose_name='Age restrictions')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('available', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], default='Yes', max_length=3, verbose_name='Available for order')),
                ('rating', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating (1-10)')),
                ('date_of_entry', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of entry')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genre', models.ManyToManyField(related_name='books', to='references.genre', verbose_name='Genre')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='references.publishinghouse', verbose_name='Publishing House')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='references.serie', verbose_name='Serie')),
                ('writer', models.ManyToManyField(related_name='books', to='references.writer', verbose_name='Writer')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
