# Generated by Django 4.2.5 on 2023-10-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
