# Generated by Django 4.2.5 on 2023-09-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
            ],
        ),
    ]
