# Generated by Django 4.2.5 on 2023-09-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_number', '0002_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='writer',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Genre'),
        ),
    ]
